### ISSUE TITLE
Integration with bpfman

### ISSUE THREAD

**Issue by shaneutt** [kubernetes-sigs/blixt#77]
[BPFD](https://github.com/redhat-et/bpfd) is a system daemon for managing BPF programs. Using BPFD for Blixt would allow us to more easily and declaratively manage our eBPF programs (using Kubernetes CRDs) and has several other benefits such as helping us avoid conflicts with other eBPF programs already running on the system.

The purpose of this task is to replace our current Aya based eBPF program loader with BPFD using the [BPFD Operator](https://bpfd.netlify.app/k8s-deployment/).
```[tasklist]
### Tasks
- [ ] Deploy bpfman in the integration test cluster to make it available to those tests
- [ ] Add an `EbpfProgram` sample that can deploy our TC programs to the cluster with bpfman
- [ ] Replace the loader method of deploying our program using the `EbpfProgram` instead in our integration tests
- [ ] Ensure we have documentation for both the bpfman, and non-bpfman deployment methods
```

**Comment by shaneutt** [comment]
At this point it looks like we should wait for BPFD to release `v0.2.0`:

https://github.com/bpfd-dev/bpfd/issues/393

As this is meant to be an important milestone which will add a little bit more stability. As soon as that's done, I think we should open this right up and get started.

**Comment by mlavacca** [comment]
> At this point it looks like we should wait for BPFD to release v0.2.0:

It looks like BPFD 0.2 has been released 🎉 Does it mean we can unblock this one, correct?

**Comment by astoycos** [comment]
Yep! I want to try and start spec-ing helping this one move forward
 this week!!!

**Comment by astoycos** [comment]
Ok So I've started this in https://github.com/astoycos/blixt/tree/bpfd-integration

Otherwise we're blocked on [having BTF support in AYA](https://discord.com/channels/855676609003651072/855676609003651075/1144639381324431360) for rust programs.

**Comment by shaneutt** [comment]
From @astoycos in #152:

> Bpfd recently changed it's name to bpfman which has broken our platform integration tests in order to fix them we'll need to pin to a version of bpfman AFTER the name change and fix a few other things.
> For now the tests are temporarily disabled.

**Comment by astoycos** [comment]
/remove-lifecycle stale

Actively working on this :)

**Comment by shaneutt** [comment]
Putting this back into triage as further discussion will be needed.

/triage needs-information

**Comment by shaneutt** [comment]
Closing this as not planned for the moment, but we will reconsider this later and may re-open if new priority arises.
